# -*- coding: utf-8 -*-
"""Telco_Churn_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MnQRJDPVRHBrnDGk8jgyBOJ_StIh1lCR
"""

# 1. Import the library we need to read the data
import pandas as pd

# 2. Read the CSV file (Make sure the name matches exactly!)
# We use 'df' which stands for DataFrame (basically a table in Python)
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

# 3. Show the first 5 rows to make sure it worked
print("Data loaded successfully!")
print(df.head())

# 1. Drop the 'customerID' column (It's useless for prediction)
df.drop('customerID', axis=1, inplace=True)

# 2. Fix 'TotalCharges' (Force it to be a number)
# errors='coerce' means: "If you find text that isn't a number, turn it into NaN (Not a Number)"
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# 3. Fill missing values (NaN) with 0, just to be safe
df['TotalCharges'].fillna(0, inplace=True)

# 4. Convert 'Churn' (The answer) from Yes/No to 1/0
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

# 5. AUTOMATIC MAGIC: Convert all other text columns to numbers
# This function 'get_dummies' finds every text column and turns it into 1s and 0s automatically.
df_clean = pd.get_dummies(df)

# 6. Show the result
print("Data Cleaned Successfully!")
print(df_clean.head())

# 1. Import the tools (The Splitter and the Brain)
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# 2. Separate the Questions (X) from the Answers (y)
# X = All the columns (Tenure, MonthlyCharges, etc.) EXCEPT 'Churn'
X = df_clean.drop('Churn', axis=1)
# y = Only the 'Churn' column (The answer we want to predict)
y = df_clean['Churn']

# 3. Split the data (80% for Training, 20% for Testing)
# test_size=0.2 means 20% is for testing.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Create the Model (The Brain)
# We are using "Random Forest" (It's like asking 100 experts for their opinion and taking the majority vote)
model = RandomForestClassifier()

# 5. Train the Model (This is where the magic happens!)
# We fit the model to the Training data only.
model.fit(X_train, y_train)

print("Training Complete! The AI has learned the patterns.")

# 1. Import the scoring tools
from sklearn.metrics import accuracy_score, confusion_matrix

# 2. Ask the model to predict the answers for the Test Data
predictions = model.predict(X_test)

# 3. Calculate the score
score = accuracy_score(y_test, predictions)

# 4. Print the result nicely
print("Accuracy Score:", score)
print("---------------------------")
print("Confusion Matrix (The detailed breakdown):")
print(confusion_matrix(y_test, predictions))